// Centralized copy: these headings can later be hydrated from an admin-managed source.
export const siteContent = {
  videosHeading: "Trending Videos",
  videosDescription: "The most-watched videos right now",
  videoFilterLabel: "Filter",
  bestVideoLabel: "Best Video",
  latestVideoLabel: "Latest Video",
  videoFilterAriaLabel: "Sort videos",
  channelFilterLabel: "Filter",
  popularChannelsLabel: "Most Videos",
  latestChannelsLabel: "Latest Channels",
  channelFilterAriaLabel: "Sort channels",
  paginationNextLabel: "Next",
  paginationAriaLabel: "Pagination",
  paginationPageLabel: "Page",
  performersHeading: "Trending Pornstars",
  performersDescription: "Discover the creators everyone is watching",
  channelsHeading: "Trending Channels",
  channelsDescription: "Studios and channels making waves",
  homeSeoHeading: "Explore Trending Videos, Creators, and Channels",
  homeSeoDescription: "Browse popular video picks, discover creators and channels, and switch between the best-performing and latest videos to find something new on Vidubuzz.",
  channelPageTitle: "Trending Channels",
  channelPageSubtitle: "Explore popular adult video channels and discover more from your favorite creators.",
  channelPageSeoHeading: "Find Popular Video Channels on Vidubuzz",
  channelPageSeoDescription: "Browse trending adult video channels on Vidubuzz, explore popular uploads, and discover featured performers and related channels.",
  channelDetailVideosHeading: "Trending Videos",
  channelDetailVideosDescription: "Browse popular uploads from this channel and sort by best or latest.",
  similarChannelsHeading: "Similar channels",
  featuredPerformersHeading: "Performers featured on this channel",
  channelDetailSeoHeading: "Explore Adult Videos and Featured Performers",
  performersPageTitle: "All Pornstars",
  performersPageSubtitle: "Discover popular adult video performers and explore their latest appearances.",
  performersPageFilterAriaLabel: "Sort pornstars",
  latestPerformersLabel: "Latest Pornstars",
  performersPageSeoHeading: "Browse Pornstars on Vidubuzz",
  performersPageSeoDescription: "Explore adult video performers on Vidubuzz, browse popular videos, and discover the channels and collaborations they appear in.",
  performerDetailVideosHeading: "Trending Videos",
  performerDetailVideosDescription: "Browse popular videos featuring this performer and sort by best or latest.",
  similarPerformersHeading: "Similar performers",
  featuredChannelsHeading: "Channels featuring this performer",
  performerDetailSeoHeading: "Explore Adult Videos and Featured Channels",
  categoriesPageTitle: "All Categories",
  categoriesPageSubtitle: "Explore adult video categories and browse popular uploads by topic.",
  categoriesPageSeoHeading: "Browse Adult Video Categories",
  categoriesPageSeoDescription: "Explore popular adult video categories on Vidubuzz, browse videos by topic, and discover performers and channels featured in the collection.",
  categoryDetailVideosHeading: "Videos in this category",
  categoryDetailVideosDescription: "Browse popular uploads in this category and sort by best or latest.",
  relatedCategoriesHeading: "Related categories",
};
